utswApp.config(function($routeProvider) {
    $routeProvider
        .when("/",
              {
                templateUrl:"views/viewmain.html",
                controller:"MainController"
            })
         .when("/add",
              {
                templateUrl:"views/viewadd.html",
                controller:"MainController"
            })
        .when("/help", 
              {
                templateUrl:"views/viewhelp.html",
                controller:"MainController"
               })
        .when("/samples", 
              {
                templateUrl:"views/viewsample.html"
               })
        .when("/signin", 
              {
                templateUrl:"views/signin.html",
                controller:"MainController"
               })
         .when("/cartitemdetail/:gradeName/:subjectName", 
              {
                templateUrl:"views/cartitemdetail.html",
                controller:"ShowStoreItemDetailController"
               })
        .when("/cart", 
              {
                templateUrl:"views/showcart.html",
                controller:"SimpleController"
               })
        .when("/shopping", 
              {
                templateUrl:"templates/storeshelf.html",
                controller:"SimpleController"
               })
        .otherwise({redirectTo:"/"});
});
